import pandas as pd


def preprocess(df):
    df = df.fillna(0)
    df['REL'] = df['REL'].apply(lambda x: 1 if x == 1 else 0)
    df['MALE'] = df['SEX'].apply(lambda x: 1 if x == 1 else 0)
    df['FEMALE'] = df['SEX'].apply(lambda x: 1 if x == 2 else 0)
    df['AGE'] = df['AGE'] / 100
    df['EDU01'] = df['EDU'].apply(lambda x: 1 if x == 1 else 0)
    df['EDU02'] = df['EDU'].apply(lambda x: 1 if x == 2 else 0)
    df['EDU03'] = df['EDU'].apply(lambda x: 1 if x == 3 else 0)
    df['EDU04'] = df['EDU'].apply(lambda x: 1 if x == 4 else 0)
    df['EDU05'] = df['EDU'].apply(lambda x: 1 if x == 5 else 0)
    df['EDU06'] = df['EDU'].apply(lambda x: 1 if x == 6 else 0)
    df['EDU07'] = df['EDU'].apply(lambda x: 1 if x == 7 else 0)
    df['EDU08'] = df['EDU'].apply(lambda x: 1 if x == 8 else 0)
    df['EDU09'] = df['EDU'].apply(lambda x: 1 if x == 9 else 0)
    df['EDU10'] = df['EDU'].apply(lambda x: 1 if x == 10 else 0)
    df['IND00'] = df['IND'].apply(lambda x: 1 if x == 0 else 0)
    df['IND01'] = df['IND'].apply(lambda x: 1 if x == 1 else 0)
    df['IND02'] = df['IND'].apply(lambda x: 1 if x == 2 else 0)
    df['IND03'] = df['IND'].apply(lambda x: 1 if x == 3 else 0)
    df['IND05'] = df['IND'].apply(lambda x: 1 if x == 5 else 0)
    df['IND08'] = df['IND'].apply(lambda x: 1 if x == 8 else 0)
    df['IND35'] = df['IND'].apply(lambda x: 1 if x == 35 else 0)
    df['IND36'] = df['IND'].apply(lambda x: 1 if x == 36 else 0)
    df['IND41'] = df['IND'].apply(lambda x: 1 if x == 41 else 0)
    df['IND45'] = df['IND'].apply(lambda x: 1 if x == 45 else 0)
    df['IND55'] = df['IND'].apply(lambda x: 1 if x == 55 else 0)
    df['IND49'] = df['IND'].apply(lambda x: 1 if x == 49 else 0)
    df['IND58'] = df['IND'].apply(lambda x: 1 if x == 58 else 0)
    df['IND64'] = df['IND'].apply(lambda x: 1 if x == 64 else 0)
    df['IND67'] = df['IND'].apply(lambda x: 1 if x == 67 else 0)
    df['IND69'] = df['IND'].apply(lambda x: 1 if x == 69 else 0)
    df['IND77'] = df['IND'].apply(lambda x: 1 if x == 77 else 0)
    df['IND85'] = df['IND'].apply(lambda x: 1 if x == 85 else 0)
    df['IND86'] = df['IND'].apply(lambda x: 1 if x == 86 else 0)
    df['IND90'] = df['IND'].apply(lambda x: 1 if x == 90 else 0)
    df['IND94'] = df['IND'].apply(lambda x: 1 if x == 94 else 0)
    df['IND83'] = df['IND'].apply(lambda x: 1 if x == 83 else 0)
    df['OCC00'] = df['OCC'].apply(lambda x: 1 if x == 0 else 0)
    df['OCC01'] = df['OCC'].apply(lambda x: 1 if x == 1 else 0)
    df['OCC02'] = df['OCC'].apply(lambda x: 1 if x == 2 else 0)
    df['OCC03'] = df['OCC'].apply(lambda x: 1 if x == 3 else 0)
    df['OCC04'] = df['OCC'].apply(lambda x: 1 if x == 4 else 0)
    df['OCC05'] = df['OCC'].apply(lambda x: 1 if x == 5 else 0)
    df['OCC61'] = df['OCC'].apply(lambda x: 1 if x == 61 else 0)
    df['OCC62'] = df['OCC'].apply(lambda x: 1 if x == 62 else 0)
    df['OCC63'] = df['OCC'].apply(lambda x: 1 if x == 63 else 0)
    df['OCC07'] = df['OCC'].apply(lambda x: 1 if x == 7 else 0)
    df['OCC08'] = df['OCC'].apply(lambda x: 1 if x == 8 else 0)
    df['OCC09'] = df['OCC'].apply(lambda x: 1 if x == 9 else 0)
    df['OCC10'] = df['OCC'].apply(lambda x: 1 if x == 10 else 0)
    df['WKCLASS01'] = df['WKCLASS'].apply(lambda x: 1 if x == 1 else 0)
    df['WKCLASS02'] = df['WKCLASS'].apply(lambda x: 1 if x == 2 else 0)
    df['WKCLASS03'] = df['WKCLASS'].apply(lambda x: 1 if x == 3 else 0)
    df['WKCLASS04'] = df['WKCLASS'].apply(lambda x: 1 if x == 4 else 0)
    df['WKCLASS05'] = df['WKCLASS'].apply(lambda x: 1 if x == 5 else 0)
    df['WKCLASS06'] = df['WKCLASS'].apply(lambda x: 1 if x == 6 else 0)
    df['WKCLASS07'] = df['WKCLASS'].apply(lambda x: 1 if x == 7 else 0)
    df['WKCLASS08'] = df['WKCLASS'].apply(lambda x: 1 if x == 8 else 0)
    df['WKCLASS09'] = df['WKCLASS'].apply(lambda x: 1 if x == 9 else 0)
    df['WORKPLACE02'] = df['WORKPLACE'].apply(lambda x: 1 if x == 2 else 0)
    df['WORKPLACE03'] = df['WORKPLACE'].apply(lambda x: 1 if x == 3 else 0)
    df['WORKPLACE04'] = df['WORKPLACE'].apply(lambda x: 1 if x == 4 else 0)
    df['WORKPLACE05'] = df['WORKPLACE'].apply(lambda x: 1 if x == 5 else 0)
    df['WORKPLACE07'] = df['WORKPLACE'].apply(lambda x: 1 if x == 7 else 0)
    df['WORKPLACE08'] = df['WORKPLACE'].apply(lambda x: 1 if x == 8 else 0)
    df['WORKPLACE09'] = df['WORKPLACE'].apply(lambda x: 1 if x == 9 else 0)
    df['WORKPLACE10'] = df['WORKPLACE'].apply(lambda x: 1 if x == 10 else 0)
    df['WORKPLACE13'] = df['WORKPLACE'].apply(lambda x: 1 if x == 13 else 0)
    df['WORKPLACE14'] = df['WORKPLACE'].apply(lambda x: 1 if x == 14 else 0)
    df['WORKPLACE15'] = df['WORKPLACE'].apply(lambda x: 1 if x == 15 else 0)
    df['WORKPLACE16'] = df['WORKPLACE'].apply(lambda x: 1 if x == 16 else 0)
    df['WORKPLACE17'] = df['WORKPLACE'].apply(lambda x: 1 if x == 17 else 0)
    df['WORKPLACE18'] = df['WORKPLACE'].apply(lambda x: 1 if x == 18 else 0)
    df['WORKPLACE20'] = df['WORKPLACE'].apply(lambda x: 1 if x == 20 else 0)
    df['WORKPLACE63'] = df['WORKPLACE'].apply(lambda x: 1 if x == 63 else 0)
    df['WORKPLACE64'] = df['WORKPLACE'].apply(lambda x: 1 if x == 64 else 0)
    df['WORKPLACE65'] = df['WORKPLACE'].apply(lambda x: 1 if x == 65 else 0)
    df['WORKPLACE66'] = df['WORKPLACE'].apply(lambda x: 1 if x == 66 else 0)
    df['WORKPLACE67'] = df['WORKPLACE'].apply(lambda x: 1 if x == 67 else 0)
    df['WORKPLACE68'] = df['WORKPLACE'].apply(lambda x: 1 if x == 68 else 0)
    df['MRG'] = df['MRG'].apply(lambda x: 0 if x in [91, 93, 94, 95, 96, 97] else 1)
    df['PT'] = df['PT'] - 1

    df = df.drop(
        columns=['YEAR', 'ID', 'PERSON', 'SEX', 'PROV', 'EDU', 'F_EDU', 'DPT', 'IND', 'OCC', 'IND2', 'OCC2', 'ECON',
                 'OUTPATIENT', 'INPATIENT', 'HEALTH_INS', 'HI_PAYER', 'HI_FEE', 'INSURE_ID1', 'INSURE_MONTH1',
                 'INSURE_ID2', 'INSURE_MONTH2', 'DEPENDENTS', 'BIRTH_Y', 'BIRTH_MONTH', 'SRN', 'ROC', 'INC_OLD',
                 'NHICLASS', 'WHOPAY', 'DEPEND', 'SI1CLASS', 'SI1MONTH', 'SI2CLASS', 'SI2MONTH',
                 'WKCLASS', 'WORK', 'WORKPLACE', 'EQUIV']
    )
    return df


all_df = pd.read_excel(r'..\static\excel\all.xlsx')
preprocessed_df = preprocess(all_df)
preprocessed_df.to_csv('check.csv')
