LIBNAME FIE1S "C:\Users\leo20\Desktop\Xunhaoz\College\111 Second\經濟系資料分析\sas lesson 3";
LIBNAME FIE2S "C:\Users\leo20\Desktop\Xunhaoz\College\111 Second\經濟系資料分析\sas lesson 7";


DATA SALARY;
SET FIE2S.AMT2011;
RUN;

DATA PERSON;
SET FIE1S.PERSON2011;
RUN;

%MACRO LOOP;
%DO K=2012 %TO 2021;
	DATA PERSON;
	SET PERSON FIE1S.PERSON&K;
	RUN;

	DATA SALARY;
	SET SALARY FIE2S.AMT&K;
	RUN;
%END;
%MEND;

%LOOP;

DATA SALARY;
SET SALARY;
IF PERSON=9 OR PERSON=0 THEN DELETE;
KEEP YEAR ID PERSON ITM40;
RUN;

DATA PERSON;
SET PERSON;
KEEP YEAR ID PERSON SEX IND WORKPLACE;
RUN;

PROC SORT DATA=SALARY;
BY YEAR ID PERSON;
RUN;

PROC SORT DATA=PERSON;
BY YEAR ID PERSON;
RUN;

DATA RES;
MERGE PERSON SALARY;
BY YEAR ID PERSON;
IF ITM40=. THEN DELETE;
IF WORKPLACE=3 THEN UBAN=ITM40; 
ELSE IF 63<=WORKPLACE<=68 THEN UBAN=ITM40;
ELSE COUNTRY=ITM40;
/*keep YEAR MALE FEMALE;*/
RUN;
